/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rest;

import Dao.StudentDao;
import bean.Student;
import bean.StudentMap;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.net.HttpURLConnection;
import java.net.URL;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dinh thang
 */
public class giaodien extends javax.swing.JFrame {

    public giaodien() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        buttonGroup1 = new javax.swing.ButtonGroup();
        tab2 = new javax.swing.JTabbedPane();
        tabs1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblsinhvien = new javax.swing.JTable();
        tabs2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtfullname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtmarks = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cbocountry = new javax.swing.JComboBox<>();
        rdofemale = new javax.swing.JRadioButton();
        rdomale = new javax.swing.JRadioButton();
        btnupdate = new javax.swing.JButton();
        txtcreate = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        btnreset = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        tblsinhvien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Email Adress", "Full Name", "Gender", "Marks", "Country"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblsinhvien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblsinhvienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblsinhvien);

        javax.swing.GroupLayout tabs1Layout = new javax.swing.GroupLayout(tabs1);
        tabs1.setLayout(tabs1Layout);
        tabs1Layout.setHorizontalGroup(
            tabs1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 575, Short.MAX_VALUE)
        );
        tabs1Layout.setVerticalGroup(
            tabs1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabs1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        tab2.addTab("tab1", tabs1);

        jLabel2.setText("Email Adress:");

        jLabel3.setText("Full Name:");

        jLabel4.setText("Average Marks:");

        jLabel5.setText("Country");

        cbocountry.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "việt nam", "trung quốc", "hàn quốc", "mẽo" }));

        buttonGroup1.add(rdofemale);
        rdofemale.setText("female");

        buttonGroup1.add(rdomale);
        rdomale.setText("male");
        rdomale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdomaleActionPerformed(evt);
            }
        });

        btnupdate.setText("Update");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });

        txtcreate.setText("Create");
        txtcreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcreateActionPerformed(evt);
            }
        });

        btndelete.setText("Delete");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });

        btnreset.setText("Reset");
        btnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tabs2Layout = new javax.swing.GroupLayout(tabs2);
        tabs2.setLayout(tabs2Layout);
        tabs2Layout.setHorizontalGroup(
            tabs2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabs2Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(tabs2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtfullname, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(tabs2Layout.createSequentialGroup()
                        .addGroup(tabs2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtmarks, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(62, 62, 62)
                        .addGroup(tabs2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(tabs2Layout.createSequentialGroup()
                                .addComponent(cbocountry, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(rdofemale)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rdomale))))
                    .addGroup(tabs2Layout.createSequentialGroup()
                        .addComponent(txtcreate)
                        .addGap(34, 34, 34)
                        .addComponent(btnupdate)
                        .addGap(29, 29, 29)
                        .addComponent(btndelete)
                        .addGap(18, 18, 18)
                        .addComponent(btnreset)))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        tabs2Layout.setVerticalGroup(
            tabs2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabs2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(txtfullname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(tabs2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(tabs2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtmarks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbocountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdofemale)
                    .addComponent(rdomale))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(tabs2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnupdate)
                    .addComponent(btndelete)
                    .addComponent(btnreset)
                    .addComponent(txtcreate))
                .addGap(22, 22, 22))
        );

        tab2.addTab("tab2", tabs2);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Quản Lý Sinh Viên");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(tab2, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addGap(43, 43, 43)
                .addComponent(tab2, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        this.load();
    }//GEN-LAST:event_formWindowOpened

    private void rdomaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdomaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdomaleActionPerformed

    private void txtcreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcreateActionPerformed
        // TODO add your handling code here:
        this.create();
        this.reset();
        this.load();
        
    }//GEN-LAST:event_txtcreateActionPerformed

    private void tblsinhvienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblsinhvienMouseClicked
        // TODO add your handling code here:
        
        if(evt.getClickCount()==2){
            int row = tblsinhvien.getSelectedRow();
            String key =(String)items.keySet().toArray()[row];
            this.edit(key);
            tab2.setSelectedIndex(1);
        }
    }//GEN-LAST:event_tblsinhvienMouseClicked

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        // TODO add your handling code here:
        this.update();
        this.load();
    }//GEN-LAST:event_btnupdateActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        // TODO add your handling code here:
        this.delete();
        this.reset();
        this.load();
    }//GEN-LAST:event_btndeleteActionPerformed

    private void btnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresetActionPerformed
        // TODO add your handling code here:
        this.reset();
        this.load();
    }//GEN-LAST:event_btnresetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(giaodien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(giaodien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(giaodien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(giaodien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
     
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new giaodien().setVisible(true);
            }
        });
    }
    // khai baso objectmapper   
//  private static ObjectMapper mapper = new ObjectMapper();
//    //lấy dữ liệu từ firebase
//    private static JsonNode request(String method,String path,Object data){
//        try {
//            String uri ="https://poly-java-6-13436-default-rtdb.firebaseio.com";
//            URL url =new URL(uri);
//            HttpURLConnection conn = (HttpURLConnection) url.openConnection();
//            conn.setRequestProperty("Accept", "application/json");  
//            conn.setRequestMethod(method);
//            if (method.equalsIgnoreCase("POST")|| method.equalsIgnoreCase("PUT")) {
//                conn.setDoOutput(true);
//                mapper.writeValue(conn.getOutputStream(),data);
//            }
//            int responseCode = conn.getResponseCode();
//            if(responseCode==200){
//                return mapper.readTree(conn.getInputStream());
//            }
//            conn.disconnect();
//            return null;
//        } catch (Exception e) {
//            throw new RuntimeException(e);
//        }
//    }
//
//    //thêm sữ liệu 
//    public static JsonNode post(String path ,Object data){
//        return request("POST",path,data);
//    }
//    public static JsonNode put(String path, Object data){
//        return request("PUT",path,data);
//    }
//    public static void delete(String path){
//        request("DELETE", path, null);
//    }
//    public static JsonNode get(String path){
//        return request("GET", path, null);      
//                
//    }
    
    StudentDao dao = new StudentDao();
    StudentMap items;
    String key =null;
    
    void fillTable(){
    items.keySet().toArray();
        DefaultTableModel model = (DefaultTableModel) tblsinhvien.getModel();
        model.setRowCount(0);
        items.forEach((key,student)->{
            model.addRow(student.getArray());
        });
}
    
    void setForm(Student form){
        txtemail.setText(form.getEmail());
        txtfullname.setText(form.getFullname());
        txtmarks.setText(form.getMarks().toString());
        rdomale.setSelected(form.getGender());
        rdofemale.setSelected(!form.getGender());
        cbocountry.setSelectedItem(form.getCountry());
    }
    Student getForm(){
        Student student = new Student();
        student.setEmail(txtemail.getText());
        student.setFullname(txtfullname.getText());
        student.setMarks(Double.parseDouble(txtmarks.getText()));
        student.setGender(rdomale.isSelected());
        student.setGender(rdofemale.isSelected());
        student.setCountry(cbocountry.getSelectedItem().toString());
        return student;
    }
    void edit(String key){
        try {
            Student student = dao.findBykey(key);
            this.key= key;
            this.setForm(student);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "lỗi tải dữ liệu");
        }
    }
    void create(){
        try {
            Student student = this.getForm();
            this.key = dao.create(student);
            this.items.put(this.key,student);
            JOptionPane.showMessageDialog(this, "Taọ mới thành công");
        } catch (Exception e) {
                        JOptionPane.showMessageDialog(this, "Taọ mới thất bại");

        }
    }
    void update(){
        try {
            
            Student student = this.getForm();
            dao.update(this.key, student);
            this.items.put(this.key, student);
            JOptionPane.showMessageDialog(this, "Cập nhật thành công!");
        } catch (Exception e) {
                        JOptionPane.showMessageDialog(this, "Cập nhật thất bại");

        }
    }
    void delete(){
        try {
            
            dao.delete(this.key);
            this.items.remove(this.key);
            this.reset();
            JOptionPane.showMessageDialog(this, "xóa thành công");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "lỗi xóa dữ liệu");
                    
        }
    }
      void reset(){
        txtemail.setText("");
        txtfullname.setText("");
        txtmarks.setText("");
        rdomale.setSelected(true);
        cbocountry.setSelectedItem("VN");
    }
    void load(){
        try {
            this.items= dao.findAll();
            this.fillTable();
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "lỗi tải dữ liệu ");
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnreset;
    private javax.swing.JButton btnupdate;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbocountry;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JRadioButton rdofemale;
    private javax.swing.JRadioButton rdomale;
    private javax.swing.JTabbedPane tab2;
    private javax.swing.JPanel tabs1;
    private javax.swing.JPanel tabs2;
    private javax.swing.JTable tblsinhvien;
    private javax.swing.JButton txtcreate;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtfullname;
    private javax.swing.JTextField txtmarks;
    // End of variables declaration//GEN-END:variables
}
